name: tentosapp
description: Um aplicativo voltado para a contagem de pontos no truco

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter
  lottie: ^1.3.0
  nice_buttons: ^0.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/splash_screen.jpg
    - assets/lotties/splash_animation.json
    - assets/sound/

  fonts:
    - family: SuitsCards
      fonts:
        - asset: assets/icons/suits_cards/fonts/SuitsCards.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
